version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: oncall
      POSTGRES_USER: oncall
      POSTGRES_PASSWORD: oncall123
    ports:
      - "54323:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oncall -d oncall"]
      interval: 10s
      timeout: 5s
      retries: 5

  # app:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     DATABASE_URL: "postgres://oncall:oncall123@db:5432/oncall?sslmode=disable"
  #     SLACK_TOKEN: "${SLACK_TOKEN}"
  #     SLACK_CHANNEL: "${SLACK_CHANNEL:-#oncall}"
  #   restart: unless-stopped

volumes:
  postgres_data:
